name: Test, Build, and Push to Google Cloud run


on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install requirements
        run: |
          python -m pip install -r src/requirements.txt
      - name: Run tests
        env:
          MODE: "github actions"
        run: |
          pytest src/tests.py


  build_push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build container image
        run: |
          docker build --platform=linux/amd64 -f Dockerfile -t cloud-run-container .
          docker tag cloud-run-container ${{ secrets.CONTAINER_IMAGE_URL }}:latest
          docker push ${{ secrets.CONTAINER_IMAGE_URL }} --all-tags
      - name: Deploy container to Cloud run
        run: |
          gcloud run deploy serverless-py-test-run --image=${{ secrets.CONTAINER_IMAGE_URL }}:latest \
          --allow-unauthenticated \
          --region=${{ secrets.GCLOUD_REGION }} \
          --project=${{ secrets.GCLOUD_PROJECT_ID }}
