name: Test, Build, and Push to Google Cloud run


on:
  workflow_dispatch:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install requirements
        run: |
          python -m pip install -r src/requirements.txt
      - name: Run tests
        env:
          MODE: "github actions"
        run: |
          pytest src/tests.py


  build_push:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build container image
        run: |
          docker build --platform=linux/amd64 -f Dockerfile -t cloud-run-container .
          docker tag cloud-run-container-amd64 europe-southwest1-docker.pkg.dev/serverless-py-test/serverless-py-repo/serverless-py:latest
          docker tag cloud-run-container-amd64 europe-southwest1-docker.pkg.dev/serverless-py-test/serverless-py-repo/serverless-py:v1
          docker push europe-southwest1-docker.pkg.dev/serverless-py-test/serverless-py-repo/serverless-py --all-tags

